---
output: stevetemplates::cv
geometry: margin=0.9in

title: "CV"
author: Saskia Nowicki

jobtitle: "Postdoctoral Researcher, Environmental Systems Science for Policy"
address: "Geography and the Environment · University of Oxford · S Parks Road OX1 3QY, UK"
fontawesome: yes
email: saskia.nowicki@ouce.ox.ac.uk
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
phone: "+44 7464 753326"
web: saskia-nowicki.github.io
#updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

#fontfamily: mathpazo
#fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Overview

As a social-ecological systems specialist, I do solution-focused research that cuts across natural, social, and health sciences to respond to long-standing and emerging water quality risks. I work collaboratively with interdisciplinary research teams and with partners beyond academia to co-produce insight that supports just transitions for healthy freshwater ecosystems and equitable safe water service delivery.

# Employment

| *Smith School of Enterprise and the Environment, University of Oxford* \hfill Oxford, UK
| Postdoctoral researcher \hfill 06/2021 - present
| Research assistant \hfill 09/2016 - 2018

| *School of Geography and the Environment, University of Oxford* \hfill Oxford, UK
| Casual lecturer \hfill 09/2021 - present
| Teaching assistant \hfill 09/2018 - 2021

| *Dept for Environment, Food and Rural Affairs, Central Science Division* \hfill London, UK
| Policy secondment, One Health governance strategy \hfill 10/2022 - 03/2023

| *Dept of Earth Sciences, University of Oxford* \hfill Oxford, UK
| Tutor, Myanmar TIDE Programme \hfill 04/2019 - 2020

| *Oxford Policy Management, WASH Team* \hfill Oxford, UK
| Consultant \hfill 09/2016 - 01/2017

| *SRK Consulting, Geochemistry Team* \hfill Vancouver, Canada
| Consultant \hfill 06/2012 - 2015

| *Gregory-Eaves Limnology Lab, McGill University* \hfill Montreal, Canada
| Research assistant \hfill 2011

# Education

| *University of Oxford*, DPhil Water and Health \hfill 2017 - 2021
| Thesis: Data, Decisions, & Drinking-Water Safety [[view](https://ora.ox.ac.uk/objects/uuid:952a1144-59e7-4cc7-8bb9-4273556c3892)]

| *University of Oxford*, MSc Water Science, Policy and Management \hfill 2015 - 2016
| Thesis: Variability in Drinking-water Microbial Contamination Risk
| Top of class, distinction

| *McGill University*, BSc (Hons) Environmental Science \hfill 2008 - 2012
| Concentration: Water Environments and Ecosystems, Biological Stream
| First class honours, distinction

# Selected Publications

| (2024) Reinforcing feedbacks for sustainable implementation of rural drinking-water treatment technology. *ACS ES&T Water*. Laauwen M & **Nowicki** **S**. [[view](https://doi.org/10.1021/acsestwater.3c00779)]
| 
| (2023) Water chemistry poses health risks as reliance on groundwater increases: a systematic review of hydrogeochemistry research from Ethiopia and Kenya. *STOTEN*. **Nowicki S**, Birhanu B, Tanui F, Sule MN, Charles K, Olago D, & Kebede S. [[view](https://doi.org/10.1016/j.scitotenv.2023.166929)] 
| 
| (2023) Results-based funding for safe drinking water services: How a standard contract design with payment for results can accelerate safe drinking water services at scale. REACH working paper 13. University of Oxford and Uptime Global. Oxford, UK. [[view](https://reachwater.uk/resource/results-based-funding-for-safe-drinking-water-services/)] 
| 
| (2022) Fear, efficacy, and environmental health risk reporting: complex responses to water quality test results in low-income communities. *IJERPH*. **Nowicki S**, Bukachi S, Hoque S, Katuva J, Musyoka M, Sammy M, Mwaniki M, Omia D, Wambua F, & Charles, K. [[view](https://doi.org/10.3390/ijerph19010597)]
| 
| (2021) The utility of *Escherichia coli* as a contamination indicator for rural drinking water: evidence from whole genome sequencing. *PLoS ONE*. **Nowicki S**, deLaurent ZR, de Villiers EP, Githinji G, & Charles KJ. [[view](https://doi.org/10.1371/journal.pone.0245910)]
| 
| (2021) Global prospects to deliver safe drinking water services for 100 million rural people by 2030. REACH Working Paper 12. RWSN and University of Oxford. Oxford, UK. [[view](https://reachwater.uk/resource/global-prospects-to-deliver-safe-drinking-water-services-for-100-million-rural-people-by-2030/)]
| 
| (2020) Including water quality monitoring in rural water services: why safe water requires challenging the quantity versus quality dichotomy. *npj Clean Water*. **Nowicki S**, Koehler J, & Charles KJ. [[view](https://doi.org/10.1038/s41545-020-0062-x)]
| 
| (2020) A framework for monitoring the safety of water services: from measurements to security. *npj Clean Water*. Charles KJ, **Nowicki S**, & Bartram JK. [[view](https://doi.org/10.1038/s41545-020-00083-1)]
| 
| (2019) Tryptophan-like fluorescence as a measure of microbial contamination risk in groundwater. *STOTEN*. **Nowicki S**, Lapworth DJ, Ward JST, Thomson P, & Charles K. [[view](https://doi.org/10.1016/j.scitotenv.2018.07.274)]

# Funding

| *Grants*
| Africa Oxford Catalyst Grant (Co-I, coordinated the application) \hfill £3500 [2024]
| UKRI MRC PHIND Grant (Co-I, led the application) \hfill £150,000 [2023-24]
| SoGE Research Environment and Culture Fund (led) \hfill £1,000 [2023]
| ESRC IAA Grant Stages 1, 2, 3 (Co-I, co-wrote the applications) \hfill £35,000 [2020-23]
| SoGE Engagement and Impact Inspiration Fund Grant (led) \hfill £1,000 [2016]
| Canada NSERC Undergraduate Research Grant (led) \hfill \$6,000 [2011]

| *Awards*
| SoGE ECR Engagement and Impact Award \hfill £500 [2022]
| McGill University Davidovic Field Study Award \hfill £1000 [2011]

| *Scholarships*
| Commonwealth Scholarship for Doctoral Study in the UK \hfill £100,000 [2017-20]
| Linacre Canadian National Scholarship & SoGE Departmental Scholarship \hfill £10,000 [2015-16]
